# Generated by Django 5.2.6 on 2025-11-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="Notifications",
        ),
    ]
