# Generated by Django 5.2.6 on 2025-11-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_notification_notifications"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notifications",
            new_name="Notification",
        ),
    ]
