# Generated by Django 5.2.6 on 2025-10-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='issued',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
