# Generated by Django 5.2.6 on 2025-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_notifications_notification"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="Notification",
        ),
    ]
