# Generated by Django 5.2.6 on 2025-10-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authcode_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='session_token',
            field=models.CharField(default='nocode', max_length=6),
        ),
    ]
