# Generated by Django 5.2.6 on 2025-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_notification_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="Notifications",
        ),
    ]
