#!/usr/bin/bash

trap "START_SERVER :: stopping everything!" SIGINT SIGTERM

if [[ $DJANGO_DEBUG == 0 ]]; then
    echo "this script requires root permissions. testing..."
    sudo echo "nice!"
fi

# create virtual env
if [ -d ".venv" ]; then
	echo "DEPLOY :: virtual environment exists"
else
	echo "DEPLOY :: creating virtual environment..."
	python3 -m venv .venv
fi

# source environment
source .venv/bin/activate
source .env

echo "DEPLOY :: installing requirements..."
pip install -r requirements.txt

echo "DEPLOY :: migrating..."
python3 manage.py migrate

if [[ $DJANGO_DEBUG == 0 ]]; then
    echo "DEPLOY :: collecting static files..."
    echo "DEPLOY :: COLLECTSTATIC :: creating static directory..."
    sudo mkdir -p ${STATIC_DIR}
    sudo chown -R admin:admin ${STATIC_DIR}
    sudo chmod -R 755 ${STATIC_DIR}
    echo "DEPLOY :: COLLECTSTATIC :: collecting static files..."
    python3 manage.py collectstatic --no-input
    sudo chown -R caddy:caddy ${STATIC_DIR}

    echo "starting application..."
    gunicorn --bind localhost:${PORT} --workers 2 --access-logfile - --capture-output --enable-stdio-inheritance base.wsgi
else
    echo "starting application..."
    python3 manage.py runserver
fi
