# Generated by Django 5.2.6 on 2025-09-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='entry_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='INCOME', max_length=10),
            preserve_default=False,
        ),
    ]
