# Generated by Django 5.2.6 on 2025-09-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_goal_amount_goal_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybudgetgoal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryincomegoal',
            name='category',
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
