# Generated by Django 5.2.6 on 2025-10-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
