# Generated by Django 5.2.6 on 2025-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="category",
                    name="goal",
                    field=models.DecimalField(
                        max_digits=12, decimal_places=2, default=0
                    ),
                ),
            ],
        ),
    ]
