# Generated by Django 5.2.6 on 2025-11-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
