# Generated by Django 5.2.6 on 2025-10-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = []
