# Generated by Django 5.2.6 on 2025-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgoal',
            name='progress_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='categorygoal',
            name='progress_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
