# Generated by Django 5.2.6 on 2025-10-02 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_category_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="progress",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
