# Generated by Django 5.2.6 on 2025-11-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_add_goal_to_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="goal",
        ),
    ]
