# Generated by Django 5.2.6 on 2025-11-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together=set(),
        ),
    ]
