# Generated by Django 5.2.6 on 2025-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_alter_category_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="progress",
        ),
        migrations.AddField(
            model_name="category",
            name="goal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
