# Generated by Django 5.2.6 on 2025-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_accountgoal_progress_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgoal',
            name='balance_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='categorygoal',
            name='balance_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
