# Generated by Django 5.2.6 on 2025-10-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_remove_category_progress_category_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
