# Generated by Django 5.2.6 on 2025-11-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_accountgoal_balance_value_categorygoal_balance_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgoal',
            name='balance_value',
        ),
        migrations.RemoveField(
            model_name='accountgoal',
            name='progress_value',
        ),
        migrations.RemoveField(
            model_name='categorygoal',
            name='balance_value',
        ),
        migrations.RemoveField(
            model_name='categorygoal',
            name='progress_value',
        ),
    ]
