sequenceDiagram
    actor User
    participant Django
    participant EmailServer
    participant MariaDB

    Note left of User: "I want to receive notifications when I’m within 10% of any of my budgets or income goals."
    Note left of User: "As a user, I want to receive notifications when I reach my budgets or income goals."
    Note left of User: Start at /dashboard
    
    opt If email notifications are enabled (asynchronous)
        Note over Django: Interval (e.g. hourly) for routine actions is reached

        Django--)MariaDB: Query pending notifications for the user
        MariaDB--)Django: Send pending notifications
        Django--)EmailServer: Queue notification if one is pending
        EmailServer--)User: Send notification
    end
    
    User->>Django: Request /

    Note over Django: Tack on a notification to the webpage, that will fire when it loads

    Django->>User: Return / with armed notification