# Generated by Django 5.2.6 on 2025-09-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountgoal",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="categorygoal",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="entry",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finances.accountgoal",
            ),
        ),
    ]
